export default {
    darkMode: "class",
    content: ["./index.html", "./src/**/*.{ts,tsx}"],
    theme: {
        extend: {
            colors: {
            surface: "#111318",
            "surface-dim": "#0D0F13",
            "surface-bright": "#232A36",
            "surface-container-lowest": "#111318",
            "surface-container-low": "#171A20",
            "surface-container": "#171A20",
            "surface-container-high": "#1A1F27",
            "surface-container-highest": "#202632",
            "on-surface": "#F3F4F6",
            "on-surface-variant": "#A7AFBF",
            "inverse-surface": "#F3F4F6",
            "inverse-on-surface": "#111318",
            outline: "#2A3140",
            "outline-variant": "#232A36",
            "surface-tint": "#4F6EF7",
            primary: "#4F6EF7",
            "on-primary": "#FFFFFF",
            "primary-container": "#4F6EF7",
            "on-primary-container": "#FFFFFF",
            "inverse-primary": "#4F6EF7",
            secondary: "#7B8496",
            "on-secondary": "#111318",
            "secondary-container": "#7B8496",
            "on-secondary-container": "#F3F4F6",
            tertiary: "#F59E0B",
            "on-tertiary": "#111318",
            "tertiary-container": "#F59E0B",
            "on-tertiary-container": "#111318",
            error: "#EF4444",
            "on-error": "#FFFFFF",
            "error-container": "#EF4444",
            "on-error-container": "#FFFFFF",
            "primary-fixed": "#4F6EF7",
            "primary-fixed-dim": "#5B78FF",
            "on-primary-fixed": "#FFFFFF",
            "on-primary-fixed-variant": "#FFFFFF",
            "secondary-fixed": "#7B8496",
            "secondary-fixed-dim": "#7B8496",
            "on-secondary-fixed": "#F3F4F6",
            "on-secondary-fixed-variant": "#F3F4F6",
            "tertiary-fixed": "#F59E0B",
            "tertiary-fixed-dim": "#F59E0B",
            "on-tertiary-fixed": "#111318",
            "on-tertiary-fixed-variant": "#111318",
            background: "#111318",
            "on-background": "#F3F4F6",
            "surface-variant": "#171A20",
            "terminal-black": "#0A0C10",
            "success-mint": "#22C55E",
            "danger-red": "#EF4444",
            "on-danger": "#FFFFFF",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                xs: "4px",
                sm: "8px",
                md: "16px",
                lg: "24px",
                xl: "32px",
                "2xl": "48px",
                "3xl": "64px",
                gutter: "16px",
                margin: "24px",
            },
            fontFamily: {
                display: ["Hanken Grotesk", "sans-serif"],
                "headline-lg": ["Hanken Grotesk", "sans-serif"],
                "headline-md": ["Hanken Grotesk", "sans-serif"],
                "body-lg": ["Hanken Grotesk", "sans-serif"],
                "body-md": ["Hanken Grotesk", "sans-serif"],
                "body-sm": ["Hanken Grotesk", "sans-serif"],
                "label-md": ["Hanken Grotesk", "sans-serif"],
                "label-sm": ["Hanken Grotesk", "sans-serif"],
                code: ["JetBrains Mono", "monospace"],
            },
            fontSize: {
                display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
                code: ["14px", { lineHeight: "22px", fontWeight: "400" }],
            },
        },
    },
    plugins: [],
};
