REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0

POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0

AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=XpzGrsGy7buZnkBBmj7s+l7eqb2BxULTYCiIChAD/A1ujbW2D6KFhPXjrVKvEDAh

ALLOW_ENABLE_NETWORK=false
ENABLE_NETWORK=false
ALLOWED_LANGUAGES_FOR_ENABLE_NETWORK=

MAX_CPU_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=15
MAX_MEMORY_LIMIT=512000
MAX_PROCESSES_AND_OR_THREADS=64
MAX_QUEUE_SIZE=200

ENABLE_WAIT_RESULT=false
ENABLE_COMPILER_OPTIONS=false
ENABLE_COMMAND_LINE_ARGUMENTS=false
